@startuml


abstract class Shape {
  + area(): double const virtual pure
  + ~Shape() virtual
}

class Circle {
  - radius: double

  + Circle(r: double)
  + area(): double const override
}

class Rectangle {
  - width: double
  - height: double

  + Rectangle(w: double, h: double)
  + area(): double const override
}

class RightTriangle {
  - base: double
  - height: double

  + RightTriangle(b: double, h: double)
  + area(): double const override
}

class Trapezoid {
  - base1: double
  - base2: double
  - height: double

  + Trapezoid(a: double, b: double, h: double)
  + area(): double const override
}

Shape <|-- Circle
Shape <|-- Rectangle
Shape <|-- RightTriangle
Shape <|-- Trapezoid


@enduml