@startuml
start

:SIZE = 6, X[6], Y[6];

  :Ввод массива X;
  :Ввод массива Y;



  :Вывод массива X;
  :Вывод массива Y;



  while (i < SIZE?)
    if (X[i] < 0?) then (да)
      :X[i] = Y[i];
    else (нет)
    endif
    :i++;
  endwhile


  :Вывод результирующего массива X;


stop
@enduml